# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Singcy's Blog"
email: singcygeorge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Singcy George''s Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://singcygeorge.cdfx.org" # the base hostname & protocol for your site
twitter_username: singcygeorge
#github_username:  singcygeorge

# Build settings
markdown: kramdown

timezone: America/New_York
encoding: utf-8
